### ISSUE TITLE
Add In not possible to import

### ISSUE THREAD

**Issue by paedeschmitt** [NexarDeveloper/nexar-supply-excel-cs#12]
Hi, unfortunantely the Add-In doesn't work.. I tried to integrate it as written in the manual.. 
As you can see the add-in was activated.. neither the ribbon appears nor '=nexar...' shows up.
Is the current file damaged? Or did I do a mistake?

thank you for your quick support.
best regards
Patrick
![image](https://user-images.githubusercontent.com/105435987/168082497-071325d4-8c98-41b0-8135-458292717295.png)

**Comment by RobAltium** [comment]
> It turned out that the links in the read me file aren't up to date. Please take latest files from bin/release: https://github.com/NexarDeveloper/nexar-supply-excel-cs/tree/main/Nexar.Supply.Xll/bin/Release

HI @paedeschmitt - thanks for raising, then resolving/closing this issue.

I went to address the issue about the README links being wrong but I think they both look correct and point at the latset XLL files (latest commit: 7a23cce).  These links I was expecting are, respecitvely for 64-bit then 32-bit:
https://github.com/NexarDeveloper/nexar-supply-excel-cs/blob/main/Nexar.Supply.Xll/bin/Release/NexarSupply-AddIn64-packed.xll
https://github.com/NexarDeveloper/nexar-supply-excel-cs/blob/main/Nexar.Supply.Xll/bin/Release/NexarSupply-AddIn-packed.xll

Please let me know if I have missed something?  Your link above (using `tree` instead lf `blob`) is also good in that it points to the latest directory containing both files.

**Comment by paedeschmitt** [comment]
strange thing... yesterday it didn't work for me...
Never the less.. It would be great if you could implement the lifecycle status for me :)
please let me know if thats possible.

Have a nice Weekend
Patrick

**Comment by RobAltium** [comment]
Hi Patrick, - thanks for confirming.  

> It would be great if you could implement the lifecycle status for me :)
I hear your request for lifecycle status and I have created a ticket on our backlog (internal ref: NAPI-452) for this enhancement.  Other priorities will mean we won't get to it this week ... but it is something we want to implement, certainly.
