### ISSUE TITLE
Conrad Stock

### ISSUE THREAD

**Issue by pedroluisneves** [NexarDeveloper/nexar-supply-excel-cs#13]
Hi Rob,

I found an issue regarding Conrad stock information.
This supplier is different from others as it doesn't share the exact stock amount:
![image](https://user-images.githubusercontent.com/48982504/169618676-166f59e4-c9ff-4d7f-b7b4-66105c46de2e.png)

With the Octpart old add-in I get the message 'Yes', but with Nexar add-in I get 'Not in stock'.
![image](https://user-images.githubusercontent.com/48982504/169618763-1367000f-6947-470b-a643-46648a7e332a.png)

I haven't check the source code but it believe the add-in is not handling correctly an answer that is not a number.

PS: It seams that the 32 bit add-in is not anymore recognized as a threat by Microsoft.

Regards
Pedro Neves

**Comment by RobAltium** [comment]
Hi @pedroluisneves - thanks for your post.

I acknowledge there's a difference and have raised a ticket (internally: NAPI-473) for addressing this gap.  Good catch!  The ticket has been added to our current sprint and I hope to get to it this week.  I'll let you know when the fix is available.

Thank you for pointing out that the "false positive" mis-categorized threat has been addressed by MS.  At last!

**Comment by pedroluisneves** [comment]
Hi Rob,

Thank you for the quick feedback.
Another "issue" regarding the socks is that Nexar add-in return them as "text", creating a situation where I am not able to format the numbers to put for example a space at the thousands digit.

Regards
Pedro Neves

**Comment by pedroluisneves** [comment]
Hi Rob, I would love to test the new version but it's again spotted as virus.
![image](https://user-images.githubusercontent.com/48982504/170245009-988480cc-eb4b-47ad-8a00-f8dc1082cd61.png)

**Comment by RobAltium** [comment]
> Hi Rob, I would love to test the new version but it's again spotted as virus.

Oh that's a pain for you!  You should work with your IT department to come up to speed with the very latest AV definitions.  
In the meantime if you want to message me with an email or similar I could try and help you.

I shall close this particular issue as the stock issue is resolved.
