### ISSUE TITLE
Add component description

### ISSUE THREAD

**Issue by vpapanik** [NexarDeveloper/nexar-supply-excel-cs#16]
Simple as that :) it would be VERY useful !!!

**Comment by RobAltium** [comment]
![image](https://user-images.githubusercontent.com/75626416/176742466-08df5e9c-e5e2-45d5-804d-4bad3ba92613.png)

Hi @vpapanik - is this the sort of thing you're after?

**Comment by vpapanik** [comment]
> ![image](https://user-images.githubusercontent.com/75626416/176742466-08df5e9c-e5e2-45d5-804d-4bad3ba92613.png)
> 
> Hi @vpapanik - is this the sort of thing you're after?

yes, the short description, is it already available ?

**Comment by RobAltium** [comment]
No ... but your timing is exquisite and since I was in the code anyway I thought why not.  

I shall add it and update the add-in.  Look out for v0.5 coming (hopefully) tomorrow...

**Comment by vpapanik** [comment]
> No ... but your timing is exquisite and since I was in the code anyway I thought why not.  
> 
> I shall add it and update the add-in.  Look out for v0.5 coming (hopefully) tomorrow...

That is truly amazing ! I was waiting for this feature for years, since the first Octopart release... no GitHub back then, and could not do it myself 😁

Thanks a million !

**Comment by RobAltium** [comment]
If you wanted to help "beta" test overnight, the binaries should be here...
https://github.com/NexarDeveloper/nexar-supply-excel-cs/tree/220629-rob-supportSelfServe/Nexar.Supply.Xll/bin/Release

I haven't installed them myself yet and need to test other functionality and get a review before releasing a supported version, hopefully tomorrow.  But if you're technically inclined and want to try things out, feel free.

**Comment by RobAltium** [comment]
Hi @vpapanik,
Version 0.5 of the Excel add-in is now live and includes your new function: `NEXAR_SUPPLY_SHORT_DESCRIPTION()`
Many thanks,
Rob

**Comment by vpapanik** [comment]
Thanks a lot ! I really appreciate your help !
