### ISSUE TITLE
Obsolete Part numbers

### ISSUE THREAD

**Issue by Ana-Oxit** [NexarDeveloper/nexar-supply-excel-cs#19]
Hello,

Can the status of obsolete part numbers be extracted?

Thanks 🙂

**Comment by RobAltium** [comment]
Hi @Ana-Oxit - thanks for this question too.

At the moment the Excel add-in does not support lifecycle status - either exposing that information or allowing filtering.  It's a little fiddly, technically.  

However, I agree this would be good information to make available in the add-in so I've asked our PM to put it on the list of improvements.

**Comment by RobAltium** [comment]
It's been a while so I'll close this issue as resolved.  At the present time we do not intend to expose lifecycle infomration in the Excel add-in (I mentioned it's a little fiddly) although I completely agree this would be valuable.  

Note that we have a new support service for raising questions, reporting bugs, requesting enhancements, available here: 
[https://support.nexar.com/support/home](https://support.nexar.com/support/home)
