### ISSUE TITLE
Return manufacturer part numbers that meet wildcard searches?

### ISSUE THREAD

**Issue by NameNotSure** [NexarDeveloper/nexar-supply-excel-cs#20]
Hello! Is there any way to get MFG part number data matching a wildcard search? For example, for many of our parts we don't care about a particular character so we will use a wildcard ("06035C104KAT*A"). I think the current Excel add-in only returns exact matches, but it would be nice to have an Excel function that returned maybe a delimited list of part numbers matching the input part number, similar to how the main Octopart site returns multiple part numbers. So for the above example, return "06035C104KAT2A, 06035C104KAT4A", similar to the results here https://octopart.com/search?q=06035C104KAT*A. Then the user could go query those exact part numbers for further details. The part number matching is the key limitation I see to the Excel add-in right now. Maybe the answer is that I should go learn how to use the actual API :-) As a non-software person though this would be a super useful feature to expand the capability within Excel. Thanks for your help!

**Comment by mw-altium** [comment]
Hi, thanks for getting in touch and the clear explanation of the issue :-) Unfortunately at this time we don't intend to extend the Excel add-in to support "search" in addition to exact matches.

What i would recommend is if you log in to nexar.com and try out our embedded IDE. Running queries is really simple and intuitive, and we have a range of FAQs if you need assistance, for example: https://docs.nexar.com/faq/ides-and-access#how-do-i-use-the-built-in-ide.

**Comment by RobAltium** [comment]
I'm closing this issue.  The Excel add-in is for BOM population rather than searching.
