### ISSUE TITLE
Cant see the *.xll in the addins dialogue 

### ISSUE THREAD

**Issue by chrispearce1972** [NexarDeveloper/nexar-supply-excel-cs#21]
Just will not appear regarless of which i select or where i put the xll files

![image](https://user-images.githubusercontent.com/36820335/194376546-63947dcf-9e2c-4417-bad9-199294cfb1c3.png)

**Comment by RobAltium** [comment]
Hi @chrispearce1972,

Thanks for your note.  That is odd.  Where did you download the .XLL file to?  Are you able to see it if you hit "Browse..." and navigate to the folder?  On Windows this is the Downloads folder by default.  Once you point Excel at the file it will be added to your list.

Note we have had an issue with some older anti-virus software falsely identifying one of the libraries we use as a trojan.  This has impacted a number of add-ins, not just the Nexar Supply add-in.  It's addressed now but do make sure you have the correct .XLL file and not one that has been quarantined.  You can read more on this in this [issue](https://github.com/NexarDeveloper/nexar-supply-excel-cs/issues/5).

Many thanks,

Rob

**Comment by chrispearce1972** [comment]
its downloaded to C:\git\nexar-supply-excel-cs\Nexar.Supply.Xll\bin\Release
from the github repo -
https://github.com/NexarDeveloper/nexar-supply-excel-cs.git

i suspect its some fail silent security policy pertaining to add ons - my
am an admin on my machine though but am at a loss as to why it lets me
navigate to the location but doesn't list or load it ?

[image: image.png]

**Comment by chrispearce1972** [comment]
i did also try moving the xlls to c:\temp to no avail :-(

**Comment by chrispearce1972** [comment]
[image: image.png]

this looks a bit suspicious - is your addin signed?

**Comment by chrispearce1972** [comment]
last one promise !!!

looks lie that is the problem - if I double click the 64bit packaged xll i
get

[image: image.png]

and if i "enable for this session" it at least makes the effort to appear
to load but then however my client id and secret don't work :-( possibly
cos the plugin is not trusted or some other reason.

[image: image.png]

Client Id:   baae8760-d718-49d0-96b4-ec1b4bcb4adb
Client Secret:  18f3d145-7d5b-4920-bc1c-8b1aba06d982
so i think I've come to an end of this "time saving" escapade !!!

**Comment by RobAltium** [comment]
@chrispearce1972 - OK, I am determined to help you if you'll let me! :-)

Using your client credentials - please edit your post to obfuscate your client secret!! - I was able to use my version of the add-in and make a query.  So you are set up correctly on Nexar.

I cannot see any of your images though, other than the very first one in the original post.  However, I have found you in the system and will contact you privately.  Let's get you running...

**Comment by chrispearce1972** [comment]
Ah that's annoying they were in the emails ok

**Comment by chrispearce1972** [comment]
I've embedded the screen shots from the emails - why it's not displaying them I have no idea !!  it'd be great to get this working :-)

**Comment by RobAltium** [comment]
Thanks I see the images and things make more sense now.

1. I use a very similar version here:  "Microsoft® Excel® for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20152) 64-bit"
2. Our add-in is not digitally signed.  This is something we want to do.  However, it's still on our backlog list.  It does not affect the add-in functionality.
3. My Trust Centre settings for Add-ins allows "Require Application Add-ins to be signed by Trusted Publisher" to be unchecked. 

![image](https://user-images.githubusercontent.com/75626416/194583350-32c8628a-8cff-40a2-a9f8-d19775574fc5.png)

 I wonder if this is your issue? 
 
Also, you have the correct 64-bit file can can I double check it is ~1MB in size?  (Sorry if you know this already - you probably have checked, it's just that I've seen some AV just replace files with a text file with "This has been quarantined" content.)

Once successfully installed you should see something like this, along with the new ribbon entry.

![image](https://user-images.githubusercontent.com/75626416/194584610-44dd53c5-b06b-4707-90e1-d53adbf9f871.png)

**Comment by chrispearce1972** [comment]
looks fine 
![image](https://user-images.githubusercontent.com/36820335/194586413-71ebd641-a182-42a1-95e8-da0569f8d65f.png)

I cannot uncheck the "trusted addins must be signed" as this must be set in the group policy which requires arguing with IT people which is only one step away from arguing with HR people....

**Comment by RobAltium** [comment]
Hi @chrispearce1972 ,

I'm glad this issue is understood and resolved, and you've got the add-in working now.

Thanks for the registry tip about working around the requirement of a signed add-in.

Let me know if you have any further questions.

Best regards,

Rob

**Comment by RobAltium** [comment]
It's been a while, so I'm closing this issue as resolved.
