### ISSUE TITLE
Parameter data

### ISSUE THREAD

**Issue by paulgovan** [NexarDeveloper/nexar-supply-excel-cs#28]
Hello, is it possible to pull parameter data with the add in?

**Comment by RobAltium** [comment]
Hi @paulgovan - not today, there is no support for `specs`.  
Although some technical information such a short description and datasheet is surfaced.  But not the key-value attributes.  
I'd encourage you to raise an enhancement request ticket here though to log your request:
https://support.nexar.com/support/tickets/new

**Comment by paulgovan** [comment]
Thanks for the advice. Cheers.
